# example config for CuNeRF

# training
max_iter : 250000
eval_iter: 10000
save_iter: $eval_iter
log_iter : 100
bs_train : 2048 # batch size 
bs_eval  : 2048
bs_test  : $bs_eval
N_eval   : 5  ####
lr       : 0.002
lr_final : 0.00002
workers  : 4

# modeling
stype     : cube
radius    : 1
n_samples : 64
n_imps    : 128
mtype     : NeRFMLP

# test
# zpos      : [0]
# scales    : [1]
# angles    : [0]
# asteps    : 45
# axis      : [0, 1, 1]
# cam_scale : 1.5
zpos      : [-0.1, 0.1]
scales    : [2]
angles    : [0, 30, 60, 90]
asteps    : 45
axis      : [0, 1, 1]
cam_scale : 1.5


# path
result_path : save
save_path   : save
log_path    : save

loss : 
  name : Adaptive_MSE_LOSS

sampling : 
  stype     : $stype
  n_samples : $n_samples

rendering :
  stype : $stype

importance :
  stype     : $stype
  n_samples : $n_imps

model : 
  name    : $mtype
  netD    : 8
  netW    : 256
  in_ch   : 3
  out_ch  : 2
  skips   : [4, 8]
  max_freq: 10
  p_fns   : ['sin', 'cos']

model_ft : $model

dataset : 
  mode : $mode
  dname: Medical3D
  train : 
    file    : $file
    scale   : $scale
    radius  : $radius
    bsize   : $bs_train
    modality: $modality 

  eval :
    file    : $file
    scale   : $scale
    radius  : $radius
    N_eval  : $N_eval
    bsize   : $bs_eval
    modality: $modality 

  test :
    file      : $file
    scales    : $scales
    radius    : $radius
    axis      : $axis
    angles    : $angles
    zpos      : $zpos
    cam_scale : $cam_scale
    asteps    : $asteps

dataloader :
  mode : $mode
  train :
    batch_size : 1
    shuffle : True
  
  eval:
    batch_size : 1
    shuffle : False

  test:
    batch_size : 1
    shuffle : False

optim :
  name : Adam
  lr   : $lr
  betas: [0.9, 0.999]
  eps  : 0.000001

metrics : 
  psnr  : True
  ssim  : True
  lpips : False
  avg   : False

lr_decay : 
  lr_init        : $lr
  lr_final       : $lr_final
  max_iter       : $max_iter
  lr_delay_steps : 1000
  lr_delay_mult  : 0.01

clip_grad :
  max_val  : 0.1
  max_norm : 0.1